name: jasontors
favicon: null
layout_spectrum: 0.18060872820205986
typography_spectrum: 0.4357833303511143
title: Jason Tors
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.08658334705978632
  lightness: 0.1278958807233721
  saturation: 0.7707384128589183
  rhythmicContrast: 0.4177716162521392
purpose: []
